//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "project_report_events")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub project_report_event_id: u32,
    pub project_report_id: u32,
    pub prev_event_id: Option<u32>,
    pub next_event_id: Option<u32>,
    #[sea_orm(column_type = "Text")]
    pub event_data: String,
    pub created: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::PrevEventId",
        to = "Column::ProjectReportEventId",
        on_update = "SetNull",
        on_delete = "SetNull"
    )]
    SelfRef2,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::NextEventId",
        to = "Column::ProjectReportEventId",
        on_update = "SetNull",
        on_delete = "SetNull"
    )]
    SelfRef1,
    #[sea_orm(
        belongs_to = "super::project_reports::Entity",
        from = "Column::ProjectReportId",
        to = "super::project_reports::Column::ProjectReportId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ProjectReports,
}

impl Related<super::project_reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectReports.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
