export { default as SaveIcon } from '@mui/icons-material/SaveOutlined';
export { default as EditIcon } from '@mui/icons-material/EditOutlined';
export { default as DeleteIcon } from '@mui/icons-material/DeleteOutlineOutlined';
export { default as ProjectIcon } from '@mui/icons-material/FolderOutlined';
export { default as OrganizationIcon } from '@mui/icons-material/CorporateFareOutlined';
export { default as SendEmailIcon } from '@mui/icons-material/EmailOutlined';
export { default as BackIcon } from '@mui/icons-material/NavigateBeforeOutlined';
export { default as NextIcon } from '@mui/icons-material/NavigateNextOutlined';
export { default as ResolveIcon } from '@mui/icons-material/CheckOutlined';