name: Pull Requests

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  validate_commits:
    name: Validate Commit Messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webiny/action-conventional-commits@v1.3.0
